### ISSUE TITLE
Error 'No JSON object could be decoded' thrown if a item from menu 'All shows' is played

### ISSUE THREAD

**Issue by X-Psi** [goggle/plugin.video.srfplaytv#11]
Since two days I got the following error when i try to play an item from the 'All shows' menu (browsing of 'All shows' is working).

NVIDIA Shield - Kodi - srfplaytv plugin V1.6

**Error Contents: No JSON object could be decoded**
```
2020-05-14 22:36:20.623 T:8567   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-05-14 22:36:26.319 T:10617   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.srfplaytv/addon.py", line 23, in <module>
                                                srfplaytv.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.srfplaytv/resources/lib/srfplaytv.py", line 136, in run
                                                SRFPlayTV().build_show_menu(name, page_hash=page_hash)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.srgssr/lib/srgssr.py", line 603, in build_show_menu
                                                json_response = json.loads(self.open_url(json_url))
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-05-14 22:36:26.422 T:10616   ERROR: GetDirectory - Error getting plugin://plugin.video.srfplaytv/?mode=20&name=c522b312-1f70-0001-f1f0-817c12301734
2020-05-14 22:36:26.439 T:8567   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.srfplaytv/?mode=20&name=c522b312-1f70-0001-f1f0-817c12301734) failed
2020-05-14 22:36:42.828 T:8567  NOTICE: CWinSystemAndroid::DestroyWindow
2020-05-14 22:36:44.428 T:8567  NOTICE: CAndroidUtils: SetNativeResolution: 11: 1920x1080 1920x1080@59.940060
2020-05-14 22:36:44.465 T:8567  NOTICE: GL_VENDOR = NVIDIA Corporation
2020-05-14 22:36:44.465 T:8567  NOTICE: GL_RENDERER = NVIDIA Tegra
2020-05-14 22:36:44.465 T:8567  NOTICE: GL_VERSION = OpenGL ES 3.2 NVIDIA 418.00
2020-05-14 22:36:44.465 T:8567  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.20
```

I have reinstalled Kodi and the srfplaytv plugin from scratch on my NVIDIA Shield but the same error exists.

**Comment by greendeath** [comment]
:+1:

**Comment by micressor** [comment]
Same here:
* LibreELEC (Leia) 9.2.1
* Kodi v18.6
* srfplaytv plugin V1.6

**Comment by goggle** [comment]
I'm aware of the current issues with the plugins, see also https://github.com/goggle/script.module.srgssr/issues/3.
I will fix it as soon as possible.

**Comment by tobiaswaldvogel** [comment]
I made a complete rework in a fork https://github.com/tobiaswaldvogel/script.module.srgssr
Everything seems to work with this again.
I also made LiveTV with DRM working as well as subtitles.

I'm still doing some testing and was going to create a pull request.
But feel to cherry pick anything yo like

If anyone want's to test it, use install from zip with 
[fork v2.0.0rc1](https://github.com/tobiaswaldvogel/script.module.srgssr/archive/v2.0.0rc1.zip)

**Comment by goggle** [comment]
@tobiaswaldvogel Wow, that's great. Would you mind making a PR to this repository, so I could easily test it as well and preparing the new release for everyone?

**Comment by tobiaswaldvogel** [comment]
I created a PR. It is quite a bunch of changes as we need to support the old and the new API.
Also the code for play_video and the new play_video_from_urn could unified but I wanted to be sure not break anything else

**Comment by goggle** [comment]
Thanks you!
I will have a look at it this evening and maybe push some further commits onto your PR before merging.
Why do we need to support the old API? Can't we just replace the old (broken) one with the new one?

**Comment by tobiaswaldvogel** [comment]
There are several plugins depending on this one
E.g. the one for RSI
It seems that RSI is still using the old API whereas SRF is using a new one
Therefore I'm afraid we need both for some time.

**Comment by goggle** [comment]
Oh ok, I wasn't aware of that, thanks for clarifying.

**Comment by tobiaswaldvogel** [comment]
I introduced a new variable 

        if bu == 'srf':
            self.apiv3_url = self.host_url + '/play/v3/api/srf/production/'

and then in the individual functions it is checked to figure out if the new API can be used.

**Comment by tobiaswaldvogel** [comment]
One more thing I would like to mention is that LiveTV also requires that the InputStream Adaptive addon is activated, which is not by default.

**Comment by tobiaswaldvogel** [comment]
I added now also the radio channels to SRF.ch live

**Comment by tobru** [comment]
I just wanted to say thanks to @tobiaswaldvogel and @goggle for the hard work on this Kodi add-on! Looking forward to a new release containing this API v3 support included.

**Comment by MrReSc** [comment]
I am also looking forward to the new release. This is the most used addon at our home.

**Comment by goggle** [comment]
I'm sorry, I don't have too much time for this right now...
I probably need to add some changes to @tobiaswaldvogel's work before I can release a new version.

**Comment by rick0ff** [comment]
@goggle / @tobiaswaldvogel are there any news concerning the changes? This is also the most used addon on my Kodi. :) Thanks for making the addon so awesome until now! 👍

**Comment by eflavio** [comment]
@goggle / @tobiaswaldvogel are there any news concerning the changes?

**Comment by kruthoff** [comment]
I'm waiting, too... 🤔

**Comment by Flo3561** [comment]
Any chance of getting an upgrade?

**Comment by rotsch105** [comment]
First: Thank you for this plugin in the last years. Great work!
Is there a working code around? I tried the tag 1.7.0 on tobiaswaldvogels fork too (install from zip). But this didn't work.
Thank you for every hint.
Roger

**Comment by goggle** [comment]
Development for `Krypton` and `Leia` has been discontinued.
The plugin should work fine in the `master` branch and will hopefully be released soon in the official Kodi addon repository (https://github.com/xbmc/repo-plugins/pull/3971)
